version: '3.7'

services:
  search-service:
    image: mac2work/yca-search:0.0.1-SNAPSHOT
    mem_limit: 700m
    restart: on-failure
    ports:
      - "8000-8099:8000"
    networks:
      - yacht-network
    depends_on:
      - discovery-server
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/yacht-charter
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://discovery-server:8761/eureka
  pricing-service:
    image: mac2work/yca-pricing:0.0.1-SNAPSHOT
    mem_limit: 700m
    restart: on-failure
    ports:
      - "8100-8199:8100"
    networks:
      - yacht-network
    depends_on:
      - discovery-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://discovery-server:8761/eureka
  orders-service:
    image: mac2work/yca-orders:0.0.1-SNAPSHOT
    mem_limit: 700m
    restart: on-failure
    ports:
      - "8200-8299:8200"
    networks:
      - yacht-network
    depends_on:
      - discovery-server
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/yacht-charter
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://discovery-server:8761/eureka
  user-panel:
    image: mac2work/yca-user-panel:0.0.1-SNAPSHOT
    mem_limit: 700m
    restart: on-failure
    ports:
      - "8300-8399:8300"
    networks:
      - yacht-network
    depends_on:
      - discovery-server
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/yacht-charter
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://discovery-server:8761/eureka
  api-gateway:
    image: mac2work/yca-api-gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    restart: on-failure
    ports:
      - "8765:8765"
    networks:
      - yacht-network
    depends_on:
      - discovery-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://discovery-server:8761/eureka
  discovery-server:
    image: mac2work/yca-discovery-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    restart: on-failure
    ports:
      - "8761:8761"
    networks:
      - yacht-network
  config-server:
    image: mac2work/yca-config-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8888:8888"
    networks:
      - yacht-network
    depends_on:
      - discovery-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://discovery-server:8761/eureka
  mysqldb:
    container_name: mysqldb
    image: mysql
    restart: on-failure
    ports:
      - "3307:3306"
    networks:
      - yacht-network
    depends_on:
      - discovery-server
    environment:
      - MYSQL_DATABASE=yacht-charter
      - MYSQL_USER=mac2work
      - MYSQL_PASSWORD=mac2work
      - MYSQL_ROOT_PASSWORD=mac2work
    volumes:
      - mysql-data:/var/lib/mysql
networks:
  yacht-network:
volumes:
  mysql-data: