spring:
 cloud:
   gateway:
     routes:
       - id: search-service
         uri: lb://SEARCH-SERVICE
         predicates:
           - Path=/search/**
         filters:
           - JwtAuthenticationFilter
           
       - id: orders-service
         uri: lb://ORDERS-SERVICE
         predicates:
           - Path=/orders/**
         filters:
           - JwtAuthenticationFilter
           
       - id: pricing-service
         uri: lb://PRICING-SERVICE
         predicates:
           - Path=/pricing/**
         filters:
           - JwtAuthenticationFilter

       - id: user-panel
         uri: lb://USER-PANEL
         predicates:
           - Path=/auth/**
         filters:
           - JwtAuthenticationFilter

       

 application:
   name: API-GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
